# Generated by Django 4.2.7 on 2023-11-17 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name_plural": "Crew"},
        ),
        migrations.AlterModelOptions(
            name="seatclass",
            options={"verbose_name_plural": "Seat Classes"},
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seats_business",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seats_economy",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seats_first_class",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.flight",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="airport.order",
            ),
        ),
    ]
