# Generated by Django 4.2.7 on 2023-11-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_airplane_seats_business_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="seats_business",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seats_economy",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="airplane",
            name="seats_first_class",
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
