# Generated by Django 4.2.7 on 2023-11-21 14:34

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_alter_airplane_seats_business_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.country_image_file_path
            ),
        ),
    ]
